#!/bin/bash
# Puedes cambiar el número de puerto tanto en maestro como en filosofos

./maestro 9003 5 &
sleep 5
for i in 0 1 2 3 4 
do
  sleep .5  # Para que no arranquen todos a la vez
  ./filosofos  $i 127.0.0.1 9003 5  &
done